// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0M5RubljgvsfScSUqQTMD5QcnkI6WEPk',
    appId: '1:2787716651:web:aad39982c4cd7a638d446e',
    messagingSenderId: '2787716651',
    projectId: 'instagram2-8174a',
    authDomain: 'instagram2-8174a.firebaseapp.com',
    storageBucket: 'instagram2-8174a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAMOGNuguJzCnrS3RlbPyTTIm3rtLBrVc',
    appId: '1:2787716651:android:bf91fab66314e9378d446e',
    messagingSenderId: '2787716651',
    projectId: 'instagram2-8174a',
    storageBucket: 'instagram2-8174a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArUtx3tZCHO8A04twjsmQpCj5vpH4Epxo',
    appId: '1:2787716651:ios:9477f58766cbe44c8d446e',
    messagingSenderId: '2787716651',
    projectId: 'instagram2-8174a',
    storageBucket: 'instagram2-8174a.appspot.com',
    iosBundleId: 'com.example.instagram2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArUtx3tZCHO8A04twjsmQpCj5vpH4Epxo',
    appId: '1:2787716651:ios:9477f58766cbe44c8d446e',
    messagingSenderId: '2787716651',
    projectId: 'instagram2-8174a',
    storageBucket: 'instagram2-8174a.appspot.com',
    iosBundleId: 'com.example.instagram2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0M5RubljgvsfScSUqQTMD5QcnkI6WEPk',
    appId: '1:2787716651:web:68c459531dbce0668d446e',
    messagingSenderId: '2787716651',
    projectId: 'instagram2-8174a',
    authDomain: 'instagram2-8174a.firebaseapp.com',
    storageBucket: 'instagram2-8174a.appspot.com',
  );
}
